name: npm publish @1024pix/stylelint-config

on:
  workflow_dispatch:
    inputs:
      version:
        type: choice
        required: true
        options:
          - patch
          - minor
          - major

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: Setup git user
        run: |
          git config --global user.name "service+github.auto-merge@pix.fr"
          git config --global user.email "pix-service-auto-merge"
      - run: npm version ${{ inputs.version }}
      - run: git push && git push --tags
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_PUBLISH_ACCESS_TOKEN}}
